CREATE DATABASE workoutbuddies;

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    title TEXT,
    sport_type TEXT,
    image_url TEXT,
    online_url TEXT,
    workout_description TEXT,
    likes INTEGER,
    begin_datetime TIMESTAMP DEFAULT NULL,
    end_datetime TIMESTAMP DEFAULT NULL,
    init_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    user_id INTEGER,
    username TEXT,
    email TEXT,
    password_encrypted TEXT
);

INSERT INTO users (username, password_encrypted) VALUES ('admin', '$2b$10$tDy.toInXqwwANfDAjCecuxe2aTjehALYC0HQ9IP9xNPXFzLGUcuW');

INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Full Body', 'https://hips.hearstapps.com/hmg-prod/images/outdoor-pull-ups-royalty-free-image-1572876774.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T9:30:00', '2023-03-16T10:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Abs', 'https://post.healthline.com/wp-content/uploads/2020/02/man-exercising-plank-push-up-1200x628-facebook.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T10:30:00', '2023-03-16T11:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Arms', 'https://images.healthshots.com/healthshots/en/uploads/2021/08/19133704/Dos-and-donts-of-workouts.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T11:30:00', '2023-03-16T12:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Shoulders', 'https://www.muscleandfitness.com/wp-content/uploads/2016/09/Bodybuilder-Working-Out-His-Upper-Body-With-Cable-Crossover-Exercise.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T12:30:00', '2023-03-16T13:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Back', 'https://hips.hearstapps.com/hmg-prod/images/outdoor-pull-ups-royalty-free-image-1572876774.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T13:30:00', '2023-03-16T14:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Legs', 'https://images.healthshots.com/healthshots/en/uploads/2021/08/19133704/Dos-and-donts-of-workouts.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T14:30:00', '2023-03-16T15:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Chest', 'https://images.healthshots.com/healthshots/en/uploads/2021/08/19133704/Dos-and-donts-of-workouts.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T15:30:00', '2023-03-16T16:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Test1', 'https://hips.hearstapps.com/hmg-prod/images/outdoor-pull-ups-royalty-free-image-1572876774.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T16:30:00', '2023-03-16T17:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Test2', 'https://media.self.com/photos/61bcd0e05aed92fc4251b026/4:3/w_2560%2Cc_limit/GettyImages-1213234926.jpeg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-16T17:30:00', '2023-03-16T18:00:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Full Body', 'https://fitpage.in/wp-content/uploads/2021/04/Article_Banner-1-34-1.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T9:30:00', '2023-03-17T10:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Abs', 'https://images.healthshots.com/healthshots/en/uploads/2021/08/19133704/Dos-and-donts-of-workouts.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T10:30:00', '2023-03-17T11:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Arms', 'https://media.self.com/photos/61bcd0e05aed92fc4251b026/4:3/w_2560%2Cc_limit/GettyImages-1213234926.jpeg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T11:30:00', '2023-03-17T12:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Shoulders', 'https://static01.nyt.com/images/2023/02/03/multimedia/WELL-CORE-WORKOUTS2-bqwz/WELL-CORE-WORKOUTS2-bqwz-mediumSquareAt3X.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T12:30:00', '2023-03-17T13:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Back', 'https://fitpage.in/wp-content/uploads/2021/04/Article_Banner-1-34-1.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T13:30:00', '2023-03-17T14:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Legs', 'https://static01.nyt.com/images/2023/02/03/multimedia/WELL-CORE-WORKOUTS2-bqwz/WELL-CORE-WORKOUTS2-bqwz-mediumSquareAt3X.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T14:30:00', '2023-03-17T15:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Chest', 'https://assets.vogue.in/photos/5f4f5dfe0861b305e8609f09/2:3/w_2560%2Cc_limit/workout%2520fitness%2520tips.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T15:30:00', '2023-03-17T16:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Test1', 'https://hips.hearstapps.com/hmg-prod/images/outdoor-pull-ups-royalty-free-image-1572876774.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T16:30:00', '2023-03-17T17:30:00');
INSERT INTO posts (user_id, title, sport_type, image_url, online_url, workout_description, begin_datetime, end_datetime) VALUES (2, 'For Present', 'Test2', 'https://fitpage.in/wp-content/uploads/2021/04/Article_Banner-1-34-1.jpg', 'https://www.youtube.com/watch?v=ep9lHCa7F_Q', 'who says you need to get out of your seat to get your sweat on! Todays workout will prove that you dont have to go crazy over the top to get a good workout in and start to sweat. If you have a unique set of abilities where working out seated is best for you, this workout is especially for you! I want to encourage you that YOU CAN! You can get amazing results and feel amazing about yourself by committing to your health through movement. Keep your head up and just follow me. I''m so proud of how far you have come. Sit up and lets do this together!', '2023-03-17T17:30:00', '2023-03-17T18:00:00');

SELECT * FROM users WHERE id = 36;

SET timezone = 'Australia/Melbourne';